# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4dbfe65c9a33a56903d83c28ff4f7b9eebf869c45f94bfc443743f27c54bc228428187dd056955c3b651ef879e9da345e6e172b44ae9d160a7075a27cfee203

test:
  secret_key_base: f21b539536d97f8e1255fa45a86fcc486a658a55a3614edb7d4ace9500ca98599cf34f587ebc16480c8f51aaed7989d421db2c63da74f1527ef319f7a09c9a61

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
